package vcelearner;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author J.Weidehaas
 */
public class EingabeUI extends javax.swing.JFrame {

    // zum Messen der Ausführzeit
//    final long timeStart = System.nanoTime();
    
    Sitzung s = new Sitzung();
    private boolean neueLK = false;

    /**
     * Creates new form EingabeUI
     */
    public EingabeUI() {

        initComponents();

        btnAbbruch.setVisible(false);

        txtAreasAntwort = new javax.swing.JTextArea[]{txtAreaAntwortA,
            txtAreaAntwortB, txtAreaAntwortC, txtAreaAntwortD, txtAreaAntwortE,
            txtAreaAntwortF, txtAreaAntwortG, txtAreaAntwortH};
        checkBoxesAntwort = new javax.swing.JCheckBox[]{checkBoxA, checkBoxB,
            checkBoxC, checkBoxD, checkBoxE, checkBoxF, checkBoxG, checkBoxH};
        checkBoxesThema = new javax.swing.JCheckBox[]{checkBox1, checkBox2,
            checkBox3, checkBox4, checkBox5, checkBox6, checkBox7};
        fillFields();
        // Ausgabe verstrichene Zeit seit Programmstart
//        final long timeEnd = System.nanoTime(); //         
//        jLabel5.setText("Verlaufszeit der Startzeit: "
//                + (timeEnd - timeStart) / 1000000000.0 + " Sek.");
    }

    public void fillFields() {
        txtAreaFrage.setText(s.getAktuelleLernKarte().getFrage());
        txtFieldID.setText(String.valueOf(s.getAktuelleLernKarte().getId()));
        txtFieldSG.setText(String.valueOf(s.getAktuelleLernKarte().getSchwierigkeitsGrad()));
        for (int i = 0; i < 8; i++) {
            if (i < s.getAktuelleLernKarte().getpAs().size()) {
                txtAreasAntwort[i].setText(s.getAktuelleLernKarte().getpAs().get(i).getAntwort());
            } else {
                txtAreasAntwort[i].setText("");
            }
        }
        for (int i = 0; i < 8; i++) {
            if (i < s.getAktuelleLernKarte().getpAs().size()) {
                checkBoxesAntwort[i].setSelected(s.getAktuelleLernKarte().getpAs().get(i).isRichtigkeit());
            } else {
                checkBoxesAntwort[i].setSelected(false);
            }
        }
        for (int i = 0; i < 7; i++) {
            checkBoxesThema[i].setSelected(false);
        }
        for (ThemenBereich tB : s.getAktuelleLernKarte().gettBs()) {
            checkBoxesThema[tB.getId() - 1].setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        checkBox3 = new javax.swing.JCheckBox();
        checkBox6 = new javax.swing.JCheckBox();
        checkBox2 = new javax.swing.JCheckBox();
        checkBox7 = new javax.swing.JCheckBox();
        checkBox1 = new javax.swing.JCheckBox();
        checkBox5 = new javax.swing.JCheckBox();
        checkBox4 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaFrage = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        checkBoxE = new javax.swing.JCheckBox();
        jScrollPane27 = new javax.swing.JScrollPane();
        txtAreaAntwortC = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        txtAreaAntwortA = new javax.swing.JTextArea();
        checkBoxF = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane32 = new javax.swing.JScrollPane();
        txtAreaAntwortH = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        txtAreaAntwortE = new javax.swing.JTextArea();
        checkBoxD = new javax.swing.JCheckBox();
        jScrollPane26 = new javax.swing.JScrollPane();
        txtAreaAntwortB = new javax.swing.JTextArea();
        checkBoxC = new javax.swing.JCheckBox();
        jScrollPane30 = new javax.swing.JScrollPane();
        txtAreaAntwortF = new javax.swing.JTextArea();
        checkBoxB = new javax.swing.JCheckBox();
        checkBoxH = new javax.swing.JCheckBox();
        checkBoxG = new javax.swing.JCheckBox();
        jScrollPane31 = new javax.swing.JScrollPane();
        txtAreaAntwortG = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        txtAreaAntwortD = new javax.swing.JTextArea();
        checkBoxA = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnGoTo = new javax.swing.JButton();
        txtFieldGoToID = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAbbruch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFieldID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldSG = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        checkBox3.setText("Methods and Encapsulation");

        checkBox6.setText("Working with inheritance");

        checkBox2.setText("Working with Java data types");

        checkBox7.setText("Exception handling");

        checkBox1.setText("Java Basics ");

        checkBox5.setText("Flow Control");

        checkBox4.setText("String,StringBuilder,Arrays,and ArrayList");

        jLabel1.setText("Themengebiete:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBox1)
                            .addComponent(checkBox5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBox2)
                            .addComponent(checkBox6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(checkBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(checkBox4))
                            .addComponent(checkBox7))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBox1)
                    .addComponent(checkBox2)
                    .addComponent(checkBox3)
                    .addComponent(checkBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBox5)
                    .addComponent(checkBox6)
                    .addComponent(checkBox7))
                .addGap(5, 5, 5))
        );

        txtAreaFrage.setColumns(20);
        txtAreaFrage.setRows(5);
        txtAreaFrage.setTabSize(2);
        jScrollPane3.setViewportView(txtAreaFrage);

        checkBoxE.setText("E");
        checkBoxE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxEActionPerformed(evt);
            }
        });

        txtAreaAntwortC.setColumns(20);
        txtAreaAntwortC.setRows(5);
        txtAreaAntwortC.setTabSize(2);
        txtAreaAntwortC.setText("bla\nbla\nbla\nbla\nbla\nbla");
        jScrollPane27.setViewportView(txtAreaAntwortC);

        txtAreaAntwortA.setColumns(20);
        txtAreaAntwortA.setRows(5);
        txtAreaAntwortA.setTabSize(2);
        txtAreaAntwortA.setText("bla\nbla\nbla\nbla\nbla\nbla");
        jScrollPane25.setViewportView(txtAreaAntwortA);

        checkBoxF.setText("F");
        checkBoxF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxFActionPerformed(evt);
            }
        });

        jLabel4.setText("Antworten:");

        txtAreaAntwortH.setColumns(20);
        txtAreaAntwortH.setRows(5);
        txtAreaAntwortH.setTabSize(2);
        txtAreaAntwortH.setText("bla\nbla\nbla\nbla\nbla\nbla");
        jScrollPane32.setViewportView(txtAreaAntwortH);

        txtAreaAntwortE.setColumns(20);
        txtAreaAntwortE.setRows(5);
        txtAreaAntwortE.setTabSize(2);
        txtAreaAntwortE.setText("bla\nbla\nbla\nbla\nbla\nbla");
        jScrollPane29.setViewportView(txtAreaAntwortE);

        checkBoxD.setText("D");
        checkBoxD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDActionPerformed(evt);
            }
        });

        txtAreaAntwortB.setColumns(20);
        txtAreaAntwortB.setRows(5);
        txtAreaAntwortB.setTabSize(2);
        txtAreaAntwortB.setText("bla\nbla\nbla\nbla\nbla\nbla");
        jScrollPane26.setViewportView(txtAreaAntwortB);

        checkBoxC.setText("C");
        checkBoxC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCActionPerformed(evt);
            }
        });

        txtAreaAntwortF.setColumns(20);
        txtAreaAntwortF.setRows(5);
        txtAreaAntwortF.setTabSize(2);
        txtAreaAntwortF.setText("bla\nbla\nbla\nbla\nbla\nbla");
        jScrollPane30.setViewportView(txtAreaAntwortF);

        checkBoxB.setText("B");
        checkBoxB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxBActionPerformed(evt);
            }
        });

        checkBoxH.setText("H");
        checkBoxH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxHActionPerformed(evt);
            }
        });

        checkBoxG.setText("G");
        checkBoxG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxGActionPerformed(evt);
            }
        });

        txtAreaAntwortG.setColumns(20);
        txtAreaAntwortG.setRows(5);
        txtAreaAntwortG.setTabSize(2);
        txtAreaAntwortG.setText("bla\nbla\nbla\nbla\nbla\nbla");
        jScrollPane31.setViewportView(txtAreaAntwortG);

        txtAreaAntwortD.setColumns(20);
        txtAreaAntwortD.setRows(5);
        txtAreaAntwortD.setTabSize(2);
        txtAreaAntwortD.setText("bla\nbla\nbla\nbla\nbla\nbla");
        jScrollPane28.setViewportView(txtAreaAntwortD);

        checkBoxA.setText("A");
        checkBoxA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkBoxA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(checkBoxD)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane28))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(checkBoxH)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checkBoxG)
                                .addComponent(checkBoxF)
                                .addComponent(checkBoxE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane29)
                                .addComponent(jScrollPane30)
                                .addComponent(jScrollPane31)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checkBoxC)
                                .addComponent(checkBoxB))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane26)
                                .addComponent(jScrollPane27)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(checkBoxA))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(checkBoxB))
                    .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(checkBoxC))
                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(checkBoxD))
                    .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(checkBoxE))
                    .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(checkBoxF))
                    .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(checkBoxG)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(checkBoxH))
                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jScrollPane1.setViewportView(jPanel2);

        jLabel2.setText("Frage:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 186, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        btnPrev.setText("<=");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText("=>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnGoTo.setText("gehe zu");
        btnGoTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToActionPerformed(evt);
            }
        });

        txtFieldGoToID.setText("ID");

        btnNew.setText("Neu");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setText("Speichern");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Löschen");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAbbruch.setText("Abbruch");
        btnAbbruch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbbruchActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        txtFieldID.setFocusable(false);
        txtFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldIDActionPerformed(evt);
            }
        });

        jLabel5.setText("Schwierigkeitsgrad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(15, 15, 15)
                                .addComponent(txtFieldSG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(btnAbbruch))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(btnGoTo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFieldGoToID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtFieldSG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGoTo)
                            .addComponent(txtFieldGoToID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbbruch))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAActionPerformed

    private void checkBoxBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxBActionPerformed

    private void checkBoxCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxCActionPerformed

    private void checkBoxDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxDActionPerformed

    private void checkBoxEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxEActionPerformed

    private void checkBoxFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxFActionPerformed

    private void checkBoxGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxGActionPerformed

    private void checkBoxHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxHActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        s.getPrevLernKarte();
        fillFields();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        s.getNextLernKarte();
        fillFields();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnGoToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToActionPerformed
        s.getById(Integer.parseInt(txtFieldGoToID.getText()));
        fillFields();
    }//GEN-LAST:event_btnGoToActionPerformed

    private void txtFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldIDActionPerformed

    }//GEN-LAST:event_txtFieldIDActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        neueLK = true;
        btnAbbruch.setVisible(true);
        btnGoTo.setVisible(false);
        btnNext.setVisible(false);
        btnPrev.setVisible(false);
        txtFieldGoToID.setVisible(false);
        txtAreaFrage.setText("");
        txtFieldID.setText(null);
        txtFieldSG.setText("0");
        for (int i = 0; i < 8; i++) {
            txtAreasAntwort[i].setText("");
        }
        for (int i = 0; i < 8; i++) {
            checkBoxesAntwort[i].setSelected(false);
        }
        for (int i = 0; i < 7; i++) {
            checkBoxesThema[i].setSelected(false);
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnAbbruchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbbruchActionPerformed
        fillFields();
        neueLK = false;
        btnAbbruch.setVisible(false);
        btnGoTo.setVisible(true);
        btnNext.setVisible(true);
        btnPrev.setVisible(true);
        txtFieldGoToID.setVisible(true);
    }//GEN-LAST:event_btnAbbruchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (!neueLK) {
            s.removeLernKarte();
            fillFields();
        } else {
            txtAreaFrage.setText("");
            txtFieldID.setText(null);
            txtFieldSG.setText(null);
            for (int i = 0; i < 8; i++) {
                txtAreasAntwort[i].setText("");
            }
            for (int i = 0; i < 8; i++) {
                checkBoxesAntwort[i].setSelected(false);
            }
            for (int i = 0; i < 7; i++) {
                checkBoxesThema[i].setSelected(false);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        LernKarte lK = new LernKarte(txtAreaFrage.getText(), Integer.parseInt(txtFieldSG.getText()));
        ArrayList<PotentielleAntwort> pAs = new ArrayList<>();
        for (int i = 0; i < txtAreasAntwort.length; i++) {
            if (!txtAreasAntwort[i].getText().equals("")) {
                PotentielleAntwort pA = new PotentielleAntwort(checkBoxesAntwort[i].isSelected(), txtAreasAntwort[i].getText());
                pAs.add(pA);
            } else {
                break;
            }
        }
        lK.setpAs(pAs);

        ArrayList<ThemenBereich> tBs = new ArrayList<>();
        for (int i = 0; i < checkBoxesThema.length; i++) {
            if (checkBoxesThema[i].isSelected()) {
                ThemenBereich tb = new ThemenBereich(i + 1, checkBoxesThema[i].getText());
                tBs.add(tb);
            }
        }
        lK.settBs(tBs);

        if (!neueLK) {
            lK.setId(s.getAktuelleLernKarte().getId());
            s.setAktuelleLernKarte(lK);
        } else {
            s.addLernKarte(lK);
            neueLK = false;
            btnAbbruch.setVisible(false);
            btnGoTo.setVisible(true);
            btnNext.setVisible(true);
            btnPrev.setVisible(true);
            txtFieldGoToID.setVisible(true);

        }

    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EingabeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EingabeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EingabeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EingabeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EingabeUI().setVisible(true);
            }
        });
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        // beim Beenden der Anwendung(Fenster schließen) wird die
        // Verbindung zur Datenbank auch beendet
        MySQLConnection.closeConnection();
    }
    private javax.swing.JTextArea[] txtAreasAntwort;
    private javax.swing.JCheckBox[] checkBoxesAntwort;
    private javax.swing.JCheckBox[] checkBoxesThema;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbbruch;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGoTo;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JCheckBox checkBox2;
    private javax.swing.JCheckBox checkBox3;
    private javax.swing.JCheckBox checkBox4;
    private javax.swing.JCheckBox checkBox5;
    private javax.swing.JCheckBox checkBox6;
    private javax.swing.JCheckBox checkBox7;
    private javax.swing.JCheckBox checkBoxA;
    private javax.swing.JCheckBox checkBoxB;
    private javax.swing.JCheckBox checkBoxC;
    private javax.swing.JCheckBox checkBoxD;
    private javax.swing.JCheckBox checkBoxE;
    private javax.swing.JCheckBox checkBoxF;
    private javax.swing.JCheckBox checkBoxG;
    private javax.swing.JCheckBox checkBoxH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JTextArea txtAreaAntwortA;
    private javax.swing.JTextArea txtAreaAntwortB;
    private javax.swing.JTextArea txtAreaAntwortC;
    private javax.swing.JTextArea txtAreaAntwortD;
    private javax.swing.JTextArea txtAreaAntwortE;
    private javax.swing.JTextArea txtAreaAntwortF;
    private javax.swing.JTextArea txtAreaAntwortG;
    private javax.swing.JTextArea txtAreaAntwortH;
    private javax.swing.JTextArea txtAreaFrage;
    private javax.swing.JTextField txtFieldGoToID;
    private javax.swing.JTextField txtFieldID;
    private javax.swing.JTextField txtFieldSG;
    // End of variables declaration//GEN-END:variables
}
